### ISSUE TITLE
Can't resolve '@theme/Unlisted' after update to Docusaurus 3.5.0

### ISSUE THREAD

**Issue by Preston-Landers** [PaloAltoNetworks/docusaurus-openapi-docs#911] opened 2024-08-09 17:30 UTC
## Describe the bug

First, thanks for the great plugin. After updating to Docusaurus 3.5.0, the build fails with:

Module not found: Error: Can't resolve '@theme/Unlisted' in '/home/planders/src/jx/jx-api-docs/node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiItem/Layout'

## Expected behavior

Compilation should continue to work.

## Current behavior

Updated to Docusaurus 3.5.0 (from 3.4.0) with the following command:

```sh
yarn upgrade @docusaurus/core@latest @docusaurus/plugin-client-redirects@latest @docusaurus/preset-classic@latest @docusaurus/eslint-plugin@latest @docusaurus/module-type-aliases@latest @docusaurus/tsconfig@latest @docusaurus/types@latest
```

Then compilation fails with:

```log
[ERROR] Client bundle compiled with errors therefore further build is impossible.
Module not found: Error: Can't resolve '@theme/Unlisted' in '/home/planders/src/jx/jx-api-docs/node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiItem/Layout'
```

## Steps to reproduce

1. Take existing working project with Docusaurus 3.4.0 and Docusaurus-Openapi-Docs 3.0.1. 
2. Run the command above to update to Docusaurus 3.5.0
3. Run `yarn build` or equivalent to see the build failure.

## Your Environment

- Version used: 3.0.1 
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Node v20.16.0
- Operating System and version (desktop or mobile):  Ubuntu 24.04
- Link to your project:

**Comment by sserrata** [comment] 2024-08-09 17:50
Hi @Preston-Landers, seems to be an undocumented breaking change introduced here: https://github.com/facebook/docusaurus/pull/10376/files

**Comment by Devon-White** [comment] 2024-08-11 14:08
I started working on a PR for this issue.

Upon upgrading the Docusaurus version, i tried two different approaches. 

1st. I tried to swap the import path and continue to use the `Unlisted` component directly.
2nd. Swapped to using the `ContentVisibility` component and passing it the `metadata` gathered from the `useDoc` function.


Doing both of these approaches leaves me with the following error:


```
react-dom.development.js:28474 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ApiItem`.
    at createFiberFromTypeAndProps (react-dom.development.js:28474:17)
    at createFiberFromElement (react-dom.development.js:28500:15)
    at reconcileSingleElement (react-dom.development.js:13987:23)
    at reconcileChildFibers (react-dom.development.js:14045:35)
    at reconcileChildren (react-dom.development.js:19182:28)
    at mountIndeterminateComponent (react-dom.development.js:20182:5)
    at beginWork (react-dom.development.js:21622:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4165:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4214:16)
    at invokeGuardedCallback (react-dom.development.js:4278:31)
react-dom.development.js:18705 The above error occurred in the <ApiItem> component:
```

If i make the `APItem` Component just render in a simple `div`, the error stops.

I'm still fairly new to React in general, so I haven't been able to discover what the root cause of the issue its. I'll continue to mess around in hopes that I can solve the issue, but a more experienced Developer might be able to make light work of this. :)

**Comment by sserrata** [comment] 2024-08-11 15:36
It's a fairly simple fix but may require breaking backward compatibility with prior releases.

**Comment by johnmcase** [comment] 2024-08-13 20:58
> Hi @Preston-Landers, seems to be an undocumented breaking change introduced here: https://github.com/facebook/docusaurus/pull/10376/files

If this is a breaking change in docusaurus should an issue be opened there for them to fix?

**Comment by sserrata** [comment] 2024-08-13 22:37
> If this is a breaking change in docusaurus should an issue be opened there for them to fix?

You could, but I doubt it would lead to a fix. Over the years, we've come to expect breaking changes to land every so often, as the semantic versioning doesn't apply to some internals. That said, I looked into it earlier today and it seems the fix will not be trivial after all. 

The bigger question is, if the solution does in fact break backward compatibility should we bump our plugin to v4?

**Comment by santhoshmurthybk** [comment] 2024-08-14 10:34
Will there be a fix rolled out for this?

**Comment by anovis** [comment] 2024-08-16 18:58
nice! thanks for the fix.  any timeline for when you think you will push this release to npm?

**Comment by robbieaverill** [comment] 2024-08-19 23:41
I just tested the latest canary release `0.0.0-763` and things build correctly.

**Comment by robbieaverill** [comment] 2024-08-21 02:12
Stable release v4.0.0 contains the fix for this

**Comment by pcolby** [comment] 2024-08-21 07:00
> [Stable release v4.0.0](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/releases/tag/v4.0.0) contains the fix for this

Confirmed working for me now (with Docusaurs 3.5.2). Thanks!

**Comment by polgiron** [comment] 2024-08-21 09:07
hello, I have installed the latest version v4.0.0, followed the readme to set up the plugin on an already set up docusaurus v3.5.2, deleted node_modules, yarn.lock and .docusaurus folder, re-installed all the packages, when I run `yarn build` I am facing this error:

```
Module not found: Error: Can't resolve '@theme/ApiItem' in '/Users/pol/www/tapestry-documentation/.docusaurus'
```

what am I doing wrong please?

**Comment by IanVS** [comment] 2024-08-26 13:17
@sserrata I attempted to upgrade to docusaurus 3.5.2 and version 4.0.1 of this plugin, and got errors.  I found that some 3.4.0 docusaurus packages are still installed, I believe due to the range on https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/e228de93d24062c46fb206548dca7af9bc6264bb/packages/docusaurus-theme-openapi-docs/package.json#L39.  This should be `^3.5.0`, to ensure that an older, incompatible version of `@docusaurus/theme-common` is not used.  I'll open a PR shortly.

**Closed** 2024-09-10 17:19 UTC
Labels: bug

**Comment by himself65** [comment] 2024-10-30 02:38
Could you please set the correct latest tag? It's very confusing

<img width="364" alt="image" src="https://github.com/user-attachments/assets/8c0c6bd5-ff8c-4826-af1b-051a906f484c">

**Comment by edgars** [comment] 2025-01-22 02:31
Hi All,

The issue is closed, but there is no proper answer, fix, or solution. 

How to fix that? 

`Module not found: Error: Can't resolve '@theme/Unlisted' in '/Users/edgar/Documents/skalena/tech/apidevportal-foundation/docs/node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiItem/Layout'`

**Comment by pcolby** [comment] 2025-01-22 02:41
hI @edgars,

> The issue is closed, but there is no proper answer, fix, or solution.

@robbieaverill [wrote above](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/911#issuecomment-2300221415):

> [Stable release v4.0.0](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/releases/tag/v4.0.0) contains the fix for this

I believe the fix is to upgrade to v4+ (note, v4 of this plugin is for v3.x of Docusaurus, currently).

If you're still seeing that error with the latest release (v4.3.1 at the time of writing), then you might be seeing something new, in which case probably worth reporting a new issue.

Cheers.
