### ISSUE TITLE
Can't resolve 'url'

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#409] opened 2023-02-08 17:25 UTC
## Describe the bug

Trying to add this package to my docusaurus 2.2 project, but I get an error now when I try to start it up.

## Expected behavior

Docusaurus starts up.

## Current behavior

failure:

```
Module not found: Error: Can't resolve 'url' in '/Users/ianvs/code/defined/dn-docs/node_modules/@paloaltonetworks/postman-code-generators/codegens/csharp-restsharp/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
	- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "url": false }
client (webpack 5.75.0) compiled with 1 error
```

## Steps to reproduce

- Clone https://github.com/IanVS/repro-docusaurus-openapi-issue
- `npm i`
- `npx docusaurus gen-api-docs all`
- `npm start`

The error happens.

## Context

I'm unable to use this plugin.

## Your Environment

- Version used: 1.5.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): node 18, Brave browser latest.
- Operating System and version (desktop or mobile): macos
- Link to your project: https://github.com/IanVS/repro-docusaurus-openapi-issue

**Comment by sserrata** [comment] 2023-02-08 19:10
Hi @IanVS, thanks for reporting this issue. I was able to reproduce but I am not sure why `url` is resolving properly in the project demo, the `docusaurus-template-openapi-docs` template, and our product developer site (which also uses this plugin). We'll continue debugging and will update if we find a root cause. For now, one workaround is to add the necessary webpack fallback to your webpack config. Alternatively, you can extend the docusaurus webpack config with this plugin:

(name it something like webpackPlugin.js and add `require.resolve("./webpackPlugin.js")` to your `themes` config.)

```
const path = require("path");
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");
const webpack = require("webpack");

module.exports = function docusaurusWebpackPolyfills() {
  return {
    name: "docusaurus-webpack-polyfills",
    configureWebpack() {
      return {
        plugins: [
          new webpack.DefinePlugin({
            "process.versions.node": JSON.stringify(
              process.versions.node || "0.0.0"
            ),
          }),
          new NodePolyfillPlugin(),
        ],
      };
    },
  };
};
```

**Comment by sserrata** [comment] 2023-02-08 19:12
Something else I noticed in your repro...

Some deep dependency resolutions are pulling in the latest Docusaurus v2.3.1 which results in the following error:

```
Hook useDoc is called outside the <DocProvider>.
```

**Comment by IanVS** [comment] 2023-02-08 19:21
Thanks for looking into this!  Where are you seeing the docusaurus 2.3.1?  I searched all through my package-lock.json for it, and don't see it.

**Comment by sserrata** [comment] 2023-02-08 19:55
@IanVS you're correct - I unintentionally introduced them after deleting `package-lock.json`. After reverting back to your lock file and including the webpack plugin  I was able to start a dev server

**Comment by IanVS** [comment] 2023-02-08 20:00
I think this still did start happening in a transitive dependency.  I have a branch from 2 weeks ago that was fine, but it started to fail after rebasing onto main, which had upgraded docusaurus.  Downgrading docusaurus didn't help, so my guess is that its one of their transitive dependencies causing the problem.

**Comment by sserrata** [comment] 2023-02-08 20:41
I was able to isolate a root cause. We maintain our own fork of the `postman-code-generators` library and recently updated it. It appears that the `csharp-restsharp` code generator was refactored to use the `url` library. That said, we'll need to update the `docusaurus-theme-openapi-docs` webpack config to ensure polyfills support for `url`. 

For now, you should be able to address the issue by  reverting to `@paloaltonetworks/postman-code-generators@1.1.13`, e.g. `npm i @paloaltonetworks/postman-code-generators@1.1.13`.

**Comment by IanVS** [comment] 2023-02-08 21:49
Thanks, I was also able to work around it for now with npm's `overrides`:

```json
{
	"overrides": {
		"@docusaurus/theme-common": "2.2.0",
		"@paloaltonetworks/postman-code-generators": "1.1.13"
	}
}
```

**Closed** 2023-02-10 22:20 UTC
Labels: bug
