### ISSUE TITLE
useTabGroupChoice no longer provided by docusaurus-theme-common

### ISSUE THREAD

**Issue by wayne-liang** [PaloAltoNetworks/docusaurus-openapi-docs#445] opened 2023-02-21 06:07 UTC
## Describe the bug

When using docusaurus-openapi-docs to generate OpenAPI 3.0-based documentation, viewing the page shows an error: "This page crashed. useTabGroupChoice is not a function".

Seems like they removed that function [in this commit](https://github.com/facebook/docusaurus/commit/9c860ce419ff90fc852a2b2d465c7ca5b07128c5#diff-9d45f93eb63de45c107ea584ca3ba0f36b07213094c59587b542c7b5a44e37fb) on Dec. 20, 2022, which seems to have gone out as part of the 2.3.0 (2023-01-26) release.

## Expected behavior

Normal page rendering.

## Current behavior

Page crashes.

## Possible solution

It seems like the `useTabGroupChoice` function has been deleted from docusaurus-theme-common, so I suppose an alternative may have to be used. Sorry, that's not a ton of help, I haven't dived into what the function used to do and if they've introduced an alternative.

## Steps to reproduce

1. Generate a basic, classic Docusaurus project (as per their [installation instructions](https://docusaurus.io/docs/installation)).
2. Install/configure docusaurus-openapi-docs as per this repo's README instructions.
3. Copy the [example Petstore yaml from OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml) into the project and make sure the configuration points at it.
4. Generate the MDX using this plugin and `npm run start`.
5. Navigate to one of the generated pages.

## Screenshots

![image](https://user-images.githubusercontent.com/21271725/220256802-fa4f1afa-d364-4a9e-af3f-7d6be651b018.png)
![image](https://user-images.githubusercontent.com/21271725/220257986-68c5510a-8515-4e21-8985-d12ab636511e.png)

## Context

Just trying out the plugin for a future documentation project, since it looks amazing!

## Your Environment

- docusaurus-plugin-openapi-docs version: 1.5.2
- docusaurus-theme-openapi-docs: 1.5.2
- Resolved @docusaurus/theme-common version in `package-lock.json`: 2.3.1
- Chrome version: Version 105.0.5195.125 (Official Build) unknown (64-bit)

**Comment by IanVS** [comment] 2023-02-21 16:08
I think this is a duplicate of https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/396.  @sserrata maybe it's worth pinning that issue for now?

**Closed** 2023-02-21 16:17 UTC
Labels: bug
