### ISSUE TITLE
Error when generating sidebars.

### ISSUE THREAD

**Issue by homotechsual** [PaloAltoNetworks/docusaurus-openapi-docs#158] opened 2022-07-12 20:48 UTC
## Describe the bug

Cannot generate site - sidebar file generating incorrect document IDs for category/tag pages.

## Expected behavior

`yarn build` should complete successfully.

## Current behavior

The following error is seen:

![image](https://user-images.githubusercontent.com/2288257/178591728-a1c8e037-9868-4658-815e-def22414d81b.png)
![image](https://user-images.githubusercontent.com/2288257/178591767-e9429e75-9bb1-476e-b89e-227ff2a94015.png)

## Possible solution

Manually correcting the paths in the output directory's sidebar.js file fixed the issue until the docs are regenerated.

## Steps to reproduce

1. Using this API definition: https://gist.github.com/homotechsual/e32d9c815c62b41501dc7d049fbd06f5
2. Config: https://gist.github.com/homotechsual/a8b7cc5f405ad97e51ed988c87426454

## Context

Documenting moderately complex REST APIs using json schemas.

**Comment by sserrata** [comment] 2022-07-13 00:09
It's possible you are missing a docsPluginId in your config. See this for more details: https://docusaurus-openapi.tryingpan.dev/#plugin-configuration-options

In your case I think setting it to "classic" should do the trick.

**Comment by sserrata** [comment] 2022-07-13 00:29
My mistake, it looks like you do have the right docsPluginId specified. I'll see if I can reproduce and will report back. Thanks.

**Comment by sserrata** [comment] 2022-07-13 13:45
Patch has been merged. Can you try again with [0.0.0-394](https://www.npmjs.com/package/docusaurus-plugin-openapi-docs/v/0.0.0-394) and report back if resolved?

**Comment by sserrata** [comment] 2022-07-14 18:17
@homotechsual any updates to report?

**Comment by homotechsual** [comment] 2022-07-14 18:20
Sorry - I will get some eyes on this tomorrow and report back - haven't had time to look at my docusaurus project in a couple of days :-D

**Comment by sserrata** [comment] 2022-07-14 19:25
No worries - we've since upgraded to beta.22 (soon to be rc.1) but you can still use [0.0.0-394](https://www.npmjs.com/package/docusaurus-plugin-openapi-docs/v/0.0.0-394) to test the fix for your particular issue.

**Comment by homotechsual** [comment] 2022-07-15 15:31
This is working perfectly now :-)

**Closed** 2022-07-15 15:44 UTC
Labels: bug

**Comment by adamsoffer** [comment] 2022-08-24 18:55
@sserrata Heads up I'm encountering the same issue. I'm on v1.1.8.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/555740/186500263-41c9d018-99c1-4396-b924-6551c7180693.png">

## Steps to reproduce
Using this API definition: https://github.com/livepeer/livepeer-studio-docs/blob/openapi/spec.yaml
Config: https://github.com/livepeer/livepeer-studio-docs/blob/openapi/docusaurus.config.js
